name: Build and update to GitHub Pages

on:
  schedule:
    # Estonia is UTC+2/+3 and data updates often happen daily ~11-12
    - cron: "15 0,8,9,10,11,18 * * *"
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          node-version: 14

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Download latest data
        run: poetry run download

      - name: Commit latest data files if updated
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "<noreply@github.com>"

          cp -a data /tmp

          for i in 1 2 3 4 5; do
            # Reset local to origin
            git fetch --all
            git reset --hard origin/master

            # Add downloaded files
            cp -f /tmp/data/* data/
            git add data
            pre-commit run

            if [[ $(git status --porcelain) ]]; then
              # Try to commit and push updates
              git commit -m "Automatic update of data files"
              git push -q "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master
            else
              echo "No updates to data"
              exit 0
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate chart data
        run: poetry run generate

      - name: Build frontend
        run: |
          cp -f data/*.json koroonakaart/src/data
          cd koroonakaart
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "<noreply@github.com>"

          SRC="$(pwd)"
          mkdir /tmp/github-pages && cd /tmp/github-pages
          git init . && git checkout --orphan "${BRANCH}"
          cp -r "${SRC}/${DEPLOY_DIR}"/* .
          [[ ! -z "${FQDN}" ]] && echo "${FQDN}" > CNAME
          git add . && git status && git commit --message "${MESSAGE}"
          git push -f -q "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "${BRANCH}"
        env:
          DEPLOY_DIR: koroonakaart/dist
          FQDN: koroonakaart.cocreators.ee
          MESSAGE: Deploy to GitHub Pages
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
